name = "aurora-comercial"
compatibility_date = "2024-01-01"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "aurora-db"
database_id = "6f854eda-873f-4c8f-bc9d-35fdebf483e1"

[ai]
binding = "AI"

[vars]
ADMIN_EMAIL = "admin@aurora.ao"
ADMIN_PASSWORD = "password123"
SECRET_KEY = "segredo-super-secreto"